/**
 * Serves /firebase-messaging-sw.js with Firebase config injected at runtime.
 * This avoids hardcoding secrets in public/ and allows env-var-driven config.
 *
 * The SW uses scope "/fcm/" so it doesn't conflict with next-pwa's sw.js at "/".
 * For push notifications, scope only matters for navigation control —
 * FCM push events always go to the registration that created the subscription.
 */
export const dynamic = 'force-dynamic'

export async function GET() {
  const config = {
    apiKey:            process.env.NEXT_PUBLIC_FIREBASE_API_KEY            ?? '',
    authDomain:        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN        ?? '',
    projectId:         process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID         ?? '',
    storageBucket:     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET     ?? '',
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? '',
    appId:             process.env.NEXT_PUBLIC_FIREBASE_APP_ID             ?? '',
  }

  const swContent = /* js */`
// Firebase Messaging Service Worker
// Auto-generated by /firebase-messaging-sw.js route — do not edit directly.

importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

// Background message handler (app is closed / not focused)
messaging.onBackgroundMessage(function(payload) {
  const notification = payload.notification || {};
  const data = payload.data || {};

  const title = notification.title || 'Dreptak';
  const options = {
    body:     notification.body || '',
    icon:     notification.icon || '/icons/icon-192.png',
    badge:    '/icons/icon-192.png',
    vibrate:  [200, 100, 200],
    tag:      data.type || 'dreptak',
    renotify: true,
    data:     data,
  };

  self.registration.showNotification(title, options);
});

// Notification click handler — navigate to deep link
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  var deepLink = (event.notification.data && event.notification.data.deep_link) || '/';
  var url = self.location.origin + deepLink;

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
      for (var i = 0; i < clientList.length; i++) {
        var client = clientList[i];
        if ('focus' in client) {
          client.focus();
          if ('navigate' in client) client.navigate(url);
          return;
        }
      }
      return clients.openWindow(url);
    })
  );
});
`

  return new Response(swContent, {
    headers: {
      'Content-Type':          'application/javascript; charset=utf-8',
      'Cache-Control':         'no-cache, no-store, must-revalidate',
      'Service-Worker-Allowed': '/',
    },
  })
}
